ALTER SESSION ENABLE SHARD DDL;


CREATE TABLESPACE SET TS_CUST_FAMILY using template (datafile size 1G autoextend on next 100m maxsize unlimited extent management local segment space management auto );

drop table ACCOUNT cascade CONSTRAINTs purge;
drop table SUBSCRIBER cascade CONSTRAINTs purge;
drop table CUST_IDENTITY cascade CONSTRAINTs purge;
drop table CUSTOMER cascade CONSTRAINTs purge;


CREATE SHARDED TABLE CUSTOMER
  ("CUST_ID" VARCHAR2(255), 
	"CUST_TYPE" VARCHAR2(4) NOT NULL, 
	"NAME" NVARCHAR2(120), 
	"BIRTH_DATE" DATE, 
	"SEX" VARCHAR2(1), 
	"NATIONALITY" NVARCHAR2(100), 
	"VIP" VARCHAR2(1), 
	"STATUS" VARCHAR2(1), 
	"AREA_CODE" VARCHAR2(25) NOT NULL DISABLE, 
	"PROVINCE" VARCHAR2(10), 
	"DISTRICT" VARCHAR2(10), 
	"PRECINCT" VARCHAR2(10), 
	"STREET_BLOCK" VARCHAR2(10), 
	"STREET" VARCHAR2(10), 
	"STREET_NAME" NVARCHAR2(200), 
	"STREET_BLOCK_NAME" NVARCHAR2(200), 
	"HOME" NVARCHAR2(200), 
	"ADDRESS" NVARCHAR2(700), 
	"CREATE_USER" VARCHAR2(50) NOT NULL, 
	"CREATE_DATETIME" DATE NOT NULL, 
	"UPDATE_DATETIME" DATE NOT NULL, 
	"UPDATE_USER" VARCHAR2(50) NOT NULL, 
	"DESCRIPTION" NVARCHAR2(512), 
	"UPDATE_NUMBER2" NUMBER(15,0), 
	"LAST_MODIFIED" TIMESTAMP (6), 
	"PARENT_ID" NUMBER(11,0), 
	"UPDATE_NUMBER" NUMBER(15,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR("UPDATE_DATETIME",'yyyymmddhh24miss'))) VIRTUAL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUST_ID)
  ) tablespace set TS_CUST_FAMILY
  partition by consistent hash (CUST_ID) partitions auto;


CREATE SHARDED TABLE ACCOUNT
("ACCOUNT_ID" VARCHAR2(255) NOT NULL,
"CUST_ID" VARCHAR2(255) NOT NULL, 
"BILL_CYCLE_ID" NUMBER(10,0) NOT NULL, 
"ACCOUNT_NO" VARCHAR2(100) NOT NULL, 
"LIMIT_USAGE" NUMBER(10,0), 
"NOTICE_CHARGE" VARCHAR2(4) NOT NULL, 
"RECEIVE_INVOICE" VARCHAR2(10), 
"END_DATETIME" DATE, 
"AREA_CODE" VARCHAR2(20) NOT NULL, 
"PROVINCE" VARCHAR2(10) NOT NULL, 
"DISTRICT" VARCHAR2(10), 
"PRECINCT" VARCHAR2(10) NOT NULL, 
"STREET_BLOCK" VARCHAR2(10), 
"STREET" VARCHAR2(10), 
"STREET_NAME" NVARCHAR2(200), 
"STREET_BLOCK_NAME" NVARCHAR2(200), 
"HOME" NVARCHAR2(200), 
"ADDRESS" NVARCHAR2(700) NOT NULL, 
"STATUS" VARCHAR2(1) NOT NULL, 
"CREATE_USER" VARCHAR2(50) NOT NULL, 
"CREATE_DATETIME" DATE NOT NULL, 
"UPDATE_USER" VARCHAR2(50) NOT NULL, 
"UPDATE_DATETIME" DATE NOT NULL, 
"PRINT_METHOD" VARCHAR2(2), 
"PAY_METHOD" VARCHAR2(5), 
"SUB_ID" NUMBER(11,0), 
"ISDN" VARCHAR2(100), 
"SIGN_DATE" DATE, 
"EFFECT_DATE" DATE, 
"UPDATE_NUMBER" NUMBER(15,0),
CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID,CUST_ID),
CONSTRAINT ACCOUNT_CUST_ID_FK FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER ON DELETE CASCADE)
tablespace set TS_CUST_FAMILY partition by reference (ACCOUNT_CUST_ID_FK) STORAGE (INITIAL 4M NEXT 4M);


CREATE SHARDED TABLE SUBSCRIBER
  ("SUB_ID" VARCHAR2(255) NOT NULL, 
	"CONTRACT_ID" NUMBER(11,0), 
	"CUST_ID" VARCHAR2(255), 
	"ACCOUNT_ID" VARCHAR2(255), 
	"TELECOM_SERVICE_ID" NUMBER(10,0), 
	"ISDN" VARCHAR2(50), 
	"IMSI" VARCHAR2(15), 
	"SERIAL" VARCHAR2(20), 
	"STATUS" VARCHAR2(1), 
	"PRODUCT_CODE" VARCHAR2(30) NOT NULL, 
	"OFFER_ID" NUMBER(10,0) NOT NULL, 
	"ACT_STATUS" CHAR(3) NOT NULL, 
	"STA_DATETIME" DATE, 
	"ACTIVE_DATETIME" DATE NOT NULL, 
	"SUB_TYPE" VARCHAR2(10), 
	"END_DATETIME" DATE, 
	"EXPIRE_DATETIME" DATE, 
	"SHOP_CODE" VARCHAR2(40) NOT NULL, 
	"DEV_STAFF_ID" NUMBER(10,0), 
	"PROMOTION_CODE" VARCHAR2(20), 
	"VIP" VARCHAR2(1), 
	"ACCOUNT" VARCHAR2(100), 
	"CREATE_DATETIME" DATE NOT NULL, 
	"CREATE_USER" VARCHAR2(30) NOT NULL, 
	"UPDATE_DATETIME" DATE NOT NULL, 
	"UPDATE_USER" VARCHAR2(30) NOT NULL, 
	"DEPOSIT" NUMBER(10,0), 
	"LIMIT_USAGE" NUMBER(10,0), 
	"PASSWORD" VARCHAR2(50), 
	"ORG_PRODUCT_CODE" VARCHAR2(30) NOT NULL, 
	"NUM_RESET_ZONE" NUMBER(10,0), 
	"START_MONEY" NUMBER(10,0), 
	"IS_INFO_COMPLETED" NUMBER(1,0), 
	"CHANNEL_TYPE_ID" NUMBER(10,0), 
	"FIRST_CONNECT" DATE, 
	"SPEED" NUMBER(10,0), 
	"KEEP_ALIVE" NUMBER(1,0), 
	"PRICE_PLAN" NUMBER(19,0), 
	"LOCAL_PRICE_PLAN" NUMBER(19,0), 
	"PROJECT" NUMBER(10,0), 
	"LOCAL_SPEED" NUMBER(10,0), 
	"TECHNOLOGY" VARCHAR2(30), 
	"NETWORK_CLASS" VARCHAR2(20), 
	"INFRASTRUCTURE_TYPE" VARCHAR2(20), 
	"DEPLOY_ACCEPT_DATE" DATE, 
	"GROUP_ID" NUMBER(10,0), 
	"IP_STATIC" VARCHAR2(30), 
	"IP_VIEW" VARCHAR2(30), 
	"IP_LAN" VARCHAR2(50), 
	"IP_WAN" VARCHAR2(50), 
	"IP_GATEWAY" VARCHAR2(50), 
	"IP_ROUTER" VARCHAR2(50), 
	"NUM_OF_COMPUTER" NUMBER(3,0), 
	"VLAN" VARCHAR2(50), 
	"UP_LINK" NUMBER(2,0), 
	"PRIVATE_IP" VARCHAR2(50), 
	"PAY_TYPE" VARCHAR2(1), 
	"UPDATE_NUMBER_1" NUMBER(15,0), 
	"REG_TYPE_ID" NUMBER(10,0), 
	"UPDATE_NUMBER3" NUMBER(15,0), 
	"TYPE" VARCHAR2(100), 
	"UPDATE_NUMBER" NUMBER(15,0),
    CONSTRAINT SUBSCRIBER_PK PRIMARY KEY (CUST_ID, SUB_ID),
    CONSTRAINT SUBSCRIBER_CUST_ID_FK FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID) ON DELETE CASCADE,
    CONSTRAINT SUBSCRIBER_ACCOUNT_ID_FK FOREIGN KEY (CUST_ID, ACCOUNT_ID) REFERENCES ACCOUNT (CUST_ID, ACCOUNT_ID) ON DELETE CASCADE
)
PARTITION BY REFERENCE (SUBSCRIBER_CUST_ID_FK)
TABLESPACE SET TS_CUST_FAMILY
STORAGE (INITIAL 4M NEXT 4M);

CREATE SHARDED TABLE CUST_IDENTITY
  ("CUST_IDENTITY_ID" VARCHAR2(255) NOT NULL, 
	"CUST_ID" VARCHAR2(255) NOT NULL, 
	"ID_TYPE" VARCHAR2(4) NOT NULL, 
	"ID_NO" VARCHAR2(20) NOT NULL, 
	"ID_ISSUE_PLACE" NVARCHAR2(200), 
	"ID_ISSUE_DATE" DATE, 
	"ID_EXPIRE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50) NOT NULL, 
	"CREATE_DATETIME" DATE NOT NULL, 
	"UPDATE_USER" VARCHAR2(50) NOT NULL, 
	"UPDATE_DATETIME" DATE NOT NULL, 
	"STATUS" VARCHAR2(1) NOT NULL, 
	"UPDATE_NUMBER2" NUMBER(15,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR("UPDATE_DATETIME",'YYYYMMDDHH24MISS'))) VIRTUAL ,
	"UPDATE_NUMBER" NUMBER(15,0) GENERATED ALWAYS AS (TO_NUMBER(TO_CHAR("UPDATE_DATETIME",'yyyymmddhh24miss'))) VIRTUAL , 
    CONSTRAINT CUST_IDENTITY_PK PRIMARY KEY (CUST_IDENTITY_ID,CUST_ID),
    CONSTRAINT CUST_IDENTITY_CUST_ID_FK FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER ON DELETE CASCADE
  ) tablespace set TS_CUST_FAMILY partition by reference (CUST_IDENTITY_CUST_ID_FK)
  STORAGE (INITIAL 4M NEXT 4M);
  
  
  
CREATE INDEX IDX_CI_IDNO_STATUS
  ON bccs_sale.cust_identity (ID_NO, STATUS, CUST_ID);

CREATE INDEX IDX_CUS_STATUS
  ON bccs_sale.customer (STATUS, CUST_ID);


CREATE INDEX IDX_SUB_CUST
  ON bccs_sale.subscriber (CUST_ID);
