INSERT INTO DATA_SUBCRIBER (DATA_SUBCRIBER_ID,
                            MSISDN,
                            SUB_ID,
                            SER_TYPE,
                            EFFECT_DATE,
                            EXPIRED_DATE,
                            SCAN_TIME,
                            SERVICE_TYPE,
                            DESCRIPTION,
                            EXTEND_TYPE,
                            PROMOTION_CODE,
                            PROMOTION_START_TIME,
                            PROMOTION_END_TIME,
                            NODE_NAME,
                            CLUSTER_NAME,
                            SUB_ID_BCCSVAS2,
                            PREFIX_MSISDN,
                            EXTEND_PROMOTION_CODE,
                            NUM_ON_FLEXIBLE)
VALUES (?,
        ?,
        ?,
        'ST5K',
        SYSDATE,
        TRUNC(SYSDATE) + 1,
        TRUNC(SYSDATE) + 1,
        '1',
        'Test',
        '3',
        '',
        '',
        '',
        'extend_fb_ht1_node1',
        'EXTEND_FB_HT1',
        '30146217018',
        '84397',
        '',
        0)
