INSERT INTO ACCOUNT (ACCOUNT_ID,
                     CUST_ID,
                     BILL_CYCLE_ID,
                     ACCOUNT_NO,
                     LIMIT_USAGE,
                     NOTICE_CHARGE,
                     RECEIVE_INVOICE,
                     END_DATETIME,
                     AREA_CODE,
                     PROVINCE,
                     DISTRICT,
                     PRECINCT,
                     STREET_BLOCK,
                     STREET,
                     STREET_NAME,
                     STREET_BLOCK_NAME,
                     HOME,
                     ADDRESS,
                     STATUS,
                     CREATE_USER,
                     CREATE_DATETIME,
                     UPDATE_USER,
                     UPDATE_DATETIME,
                     PRINT_METHOD,
                     PAY_METHOD,
                     SUB_ID,
                     ISDN,
                     SIGN_DATE,
                     EFFECT_DATE,
                     UPDATE_NUMBER)
VALUES (?, -- ACCOUNT_ID
        ?, -- CUST_ID
        1,
        LPAD(TRUNC(DBMS_RANDOM.VALUE(0, 9999999999)), 10, '0'),
        NULL,
        '4',
        NULL,
        NULL,
        'H004007004001',
        'H004',
        '007',
        '004',
        '001',
        NULL,
        NULL,
        'Tổ 1',
        NULL,
        'Tổ 1, Dịch Vọng Cầu Giấy Hà Nội',
        '2',
        'VTT1',
        TO_DATE('2025-06-12 14:02:28', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        TO_DATE('2025-12-11 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        '2',
        '00',
        60000345761,
        '24721010301',
        TO_DATE('2025-06-12', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-06-12', 'YYYY-MM-DD HH24:MI:SS'),
        NULL)
