INSERT INTO CUSTOMER (CUST_ID,
                      CUST_TYPE,
                      NAME,
                      BIRTH_DATE,
                      SEX,
                      NATIONALITY,
                      VIP,
                      STATUS,
                      AREA_CODE,
                      PROVINCE,
                      DISTRICT,
                      PRECINCT,
                      STREET_BLOCK,
                      STREET,
                      STREET_NAME,
                      STREET_BLOCK_NAME,
                      HOME,
                      ADDRESS,
                      CREATE_USER,
                      CREATE_DATETIME,
                      UPDATE_DATETIME,
                      UPDATE_USER,
                      DESCRIPTION,
                      UPDATE_NUMBER2,
                      LAST_MODIFIED,
                      PARENT_ID)
VALUES (?, -- CUST_ID
        'VIE',
        'TEST DIA BAN',
        TO_DATE('2025-06-05 09:22:51', 'YYYY-MM-DD HH24:MI:SS'),
        'M',
        'Việt Nam',
        NULL,
        '1',
        'HNI0400060',
        'HNI',
        NULL,
        '040',
        '0060',
        NULL,
        NULL,
        'Tổ 1-Bồ Đề',
        NULL,
        'Tổ 1-Bồ Đề, Phường Bồ Đề Thành phố Hà Nội',
        'VTT1',
        TO_DATE('2025-06-12 14:02:28', 'YYYY-MM-DD HH24:MI:SS'),
        TO_DATE('2025-10-14 18:17:39', 'YYYY-MM-DD HH24:MI:SS'),
        'VTT1',
        NULL,
        NULL,
        NULL,
        NULL)
